query GetInformation {
  information {
    edges {
      node {
        name
        value
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
